### PR TITLE
added un elegant terminal state check

### PR DESCRIPTION
**Pull request by halvorsenca**
as stated in the commit message this is very unelegant but should work. just a simple tuple check right now

### CODE REVIEW

**Review by caldwellc1 — CHANGES_REQUESTED** [review]
Need to make them tuples, if not going to update it.

**Comment by halvorsenca** [comment]
I changed the function check it when you can

**Review by campellcl — APPROVED** [review]

**Review by campellcl — COMMENTED** [review]
I approve, but would add comments explaining why the utility is 0 in the case where we have tuple(2,4) for readability's sake.

**Review by caldwellc1 — APPROVED** [review]

**Review by caldwellc1 — CHANGES_REQUESTED** [review]
Fix the tie state of 2 vs 4 fingers.

**Pull request closed without merging**
